#pragma once

void InputNumber(int& input, const char* msg);
void GetPerfectNumberBeetween1And500();
void IsPrimeNumer();
void GetPrimenumberRange();
void GetFactorial();
int GetPrimeNumberRecursive(int input);
void GetLastPrimeNumber();
void GetGreatestCommonDivisorOfTwoNumbers();
void GetSumOfDigit();
void GetSumOfTheSerise();
void GetCalculateTheSumOfTheSeries();
void GetCalculateTheSeries();
void GetFindTheSumOfSeriesUPToNthTerm();
void GetMaxMinAverage();
void GetNonPrimeNumbers();
void PrintSquare();
void PrintTheCubeOfNumber();
void PrintMultiplicationVerticaly();
void GetOddSum();
void GetEvenSum();
int BinarySearchRecursive(unsigned int arry[], int lIdx, int rIdx, int value);
void GetHarmonicSeriesSum();
void GetNineSumOfTheSeries();
void GetNineSumOfTheSeriesAnswer();
void GetSumOfSeriesMystery();
void GetSumOfSeriesMysteryAnswerCode();
void GetSumOfSeriesMysteryTwo();
void GetSumOfSeriesMysteryTwoAnswerCode();
void GetSumOfSeriesMysteryThree();
void GetSumOfSeriesMysteryThreeAnswerCode();
void GetFibonacci();
void GetDivisibleByNineBeetween100And200();
void GetFirstLCM();
void GetFirstLCMAnswer();
void GetReverseOrder();
void GetReverseOrderAnswer();
void GetAritimeticProgressionSeries();
void GetGeomerticProgression();
void GetStringLength();
void PrintTriangle();
void PrintTriangleTwo();
void PrintTriangleThree();
void PrintTriangleFour();